# Ports
# 4040: Spark running apps ui
# 8081: master ui (worker connection, resources allocated, aka the shit)
# 18080: history server ui

services:

  spark-master:
    image: xuanminator/spark_test
    build: .
    container_name: spark-master
    networks:
      - spark_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-master.sh; tail -f /dev/null"
    ports:
      - "8081:8080"
      - "4040:4040"
    volumes:
      - spark-events:/opt/spark/events
      - ./data:/data
      - ./scripts:/scripts

  spark-worker:
    image: xuanminator/spark_test
    depends_on:
      - spark-master
    container_name: spark-worker
    networks:
      - spark_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events
      - ./data:/data
      - ./scripts:/scripts

  spark-history-server:
    image: xuanminator/spark_test
    depends_on:
      - spark-master
    container_name: spark-history-server
    networks:
      - spark_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: /bin/bash
    # remove tail in prod
    command: -c "/opt/spark/sbin/start-history-server.sh; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events
      - ./data:/data
      - ./scripts:/scripts
    ports:
      - "18080:18080"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
      POSTGRES_DB: tpch
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - spark_network

networks:
  spark_network:
    name: spark_network
 
volumes:
  spark-events:
    name: spark-events