# Ports
# 4040: Spark running apps ui
# 8080: master ui (worker connection, resources allocated, aka the shit)
# 18080: history server ui

services:

  spark-master:
    image: xuanminator/spark_test
    build: .
    container_name: spark-master
    networks:
      - spark_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-master.sh; tail -f /dev/null"
    ports:
      - "8080:8080"
      - "4040:4040"
    volumes:
      - spark-events:/opt/spark/events

  spark-worker:
    image: xuanminator/spark_test
    build: .
    container_name: spark-worker
    networks:
      - spark_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events

  spark-history-server:
    image: xuanminator/spark_test
    build: .
    container_name: spark-history-server
    networks:
      - spark_network
    entrypoint: /bin/bash
    # remove tail in prod
    command: -c "/opt/spark/sbin/start-history-server.sh; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events
    ports:
      - "18080:18080"

networks:
  spark_network:
    name: spark_network
 
volumes:
  spark-events:
    name: spark-events